# Step 1: Create a 3x3 identity matrix called "m1"

In [14]:
import numpy as np
m1 = np.eye(3)
print(m1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Step 2: Create a vector  called "v1" with values ranging from 0 to 8

In [15]:
v1 = np.arange(9)
print(v1)

[0 1 2 3 4 5 6 7 8]


# Step 3: Reshape v1 to 3\*3 matrix called m2 

In [16]:
m2 = v1.reshape(3,3)
print(m2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Step 4: Calculate element-wise multiply on m1 and m2

In [17]:
ele_mul = m1 * m2
print(ele_mul)

[[0. 0. 0.]
 [0. 4. 0.]
 [0. 0. 8.]]


# Step 5: Add 3 on each of m1 element (called m3) 

In [18]:
m3 = m1 + 3
print(m3)

[[4. 3. 3.]
 [3. 4. 3.]
 [3. 3. 4.]]


# Step 6: Calculate m3\*m2 where * is matrix multipy  

In [19]:
max_mul = np.matmul(m3,m2)
print(max_mul)

[[27. 37. 47.]
 [30. 40. 50.]
 [33. 43. 53.]]


# Step 7: min-max normalization on m3

In [21]:
normal_m3 = (m3 - m3.min())/(m3.max() - m3.min())
print(normal_m3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Step 8: sum all of m2 value

In [22]:
print(np.sum(m2))

36


# Step 9: sum all column vector on m2 matrix

In [25]:
sum_vector = m2.T[0] + m2.T[1] + m2.T[2] 
print(sum_vector)

[ 3 12 21]


# Step 10: Create a random matrix of size 2\*3 and find the mean on each column

In [31]:
ran_matrix = np.random.random(6).reshape(2,3)
print(ran_matrix)

print(np.mean(ran_matrix, axis=0))

[[0.83233049 0.28502767 0.58809426]
 [0.89311708 0.9494435  0.78795587]]
[0.86272379 0.61723559 0.68802507]
